[package]
name = "rust"
version = "0.1.0"
authors = ["Matthias Gatto <matthias.gatto@outscale.com>"]
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
json = "0.12.4"
